/*++
Copyright (c) 2026 Microsoft Corporation

Module Name:

    date_factory.h

Abstract:

    Value factory for the theory of calendar dates.
    Values are normalized (date.mk y m d) applications; fresh values are
    generated by enumerating epoch day numbers starting at 1970-01-01.

Author:

    Angel Cui's date theory task 2026-07-04

--*/
#pragma once

#include "ast/date_decl_plugin.h"
#include "model/value_factory.h"

class date_factory final : public value_factory {
    date_util        u;
    vector<rational> m_used;   // epoch day numbers already in use
    rational         m_next;
    expr_ref_vector  m_trail;

    bool is_used(rational const& n) const {
        return m_used.contains(n);
    }

    app* mk_date(rational const& n) {
        app* v = u.mk_value_from_epoch(n);
        m_trail.push_back(v);
        return v;
    }

public:
    date_factory(ast_manager& m, family_id fid) :
        value_factory(m, fid),
        u(m),
        m_next(0),
        m_trail(m) {
    }

    expr* get_some_value(sort* s) override {
        register_value(rational(0));
        return mk_date(rational(0));
    }

    bool get_some_values(sort* s, expr_ref& v1, expr_ref& v2) override {
        register_value(rational(0));
        register_value(rational(1));
        v1 = mk_date(rational(0));
        v2 = mk_date(rational(1));
        return true;
    }

    expr* get_fresh_value(sort* s) override {
        while (is_used(m_next))
            m_next += rational::one();
        rational n = m_next;
        m_next += rational::one();
        register_value(n);
        return mk_date(n);
    }

    void register_value(expr* n) override {
        rational y, mo, d;
        if (u.is_numeral_mk(n, y, mo, d))
            register_value(date_decl_plugin::civil_to_days(y, mo, d));
    }

    void register_value(rational const& n) {
        if (!is_used(n))
            m_used.push_back(n);
    }

    void add_trail(expr* e) {
        m_trail.push_back(e);
    }
};
